name: Merge Domain Lists

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch external list and store
        run: |
          mkdir -p domains
          curl -sfL https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-raw.lst \
            -o domains/inside-raw-itdog.lst || echo "# fetch failed" > domains/inside-raw-itdog.lst

      - name: Merge and transform (optimized with awk)
        run: |
          awk '!/^#/ && NF { domains[$0] = 1 } END { for (d in domains) print "nftset=/" d "/4#inet#fw4#vpn_domains" }' \
            inside-raw.lst domains/inside-raw-itdog.lst | sort > domains/inside-dnsmasq-nfset.lst
            

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add domains/inside-raw-itdog.lst domains/inside-dnsmasq-nfset.lst
          git diff --cached --quiet || git commit -m "Update domain lists"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
